### PR TITLE
Trivial cleanup

### PR DESCRIPTION
**Pull request by kirelagin**

### CODE REVIEW

**Comment by solomatov** [comment]
I mean the whole change and addition of "!" completion item.

**Comment by kirelagin** [comment]
Well, the bug triggers exactly when a completion fires after a single key is typed.

I could come up with a brand new single-character postfix operator instead and augment the expression language of the test app with it, but that would require greater effort. I don’t think that adding a single-char completion for postfix `++` renders the test app unsuitable for whatever it can be used for if not for testing.

**Comment by kirelagin** [comment]
Actually, no, to be honest I can’t come up with any single-char unary postfix operator.
I could add, say, a dot as a prefix operator (as in `.25`), but that would require a major rewrite of the parser.

**Comment by kirelagin** [comment]
Oh, wait! Factorial! Factorial is an unary postfix operator. Do you want me to properly add it to the language (i.e. FactorialExpr, etc.)?

**Comment by solomatov** [comment]
@kirelagin Let's add factorial to that small language. It will make it more real which is always good in case of tests.

**Comment by solomatov** [comment]
I close this pull request, please, create a new pull request for this change.

**Pull request closed without merging**
