### PR TITLE
Error messages in SimpleHybridSynchronizer

### PR DESCRIPTION
**Pull request by CheatEx**

### CODE REVIEW

**Comment by solomatov** [comment]
I can't merge this change. Could you please update it.

**Comment by CheatEx** [comment]
@solomatov I resolved the conflicts, please try again.

**Comment by solomatov** [comment]
@CheatEx Please, get rid of protected fields. Using them here is a bad practice.

**Comment by CheatEx** [comment]
@solomatov Done, please take a look.

**Pull request merged**
