### PR TITLE
public access to selection

### PR DESCRIPTION
**Pull request by CheatEx**

### CODE REVIEW

**Comment by timzam** [comment]
Looks good to me.

**Comment by solomatov** [comment]
Why do you need this? Could you describe the use case? It's always suspicious when somebody opens up private stuff.

**Comment by CheatEx** [comment]
@solomatov I need to watch current selection to show to other users. I can think of only wto alternative solutions:
* Keep this property private, write a static implementation of `isLowerPrioritySelection` and store only selection (the one returned from the `selection()` method) list as a different property. It doesn't bring much abstarction IMHO.
* Create a new API somwhere on the CellContainer level. Don't have a good design for it as (a)selection is represented as a cell list for hybrid editors and as a model list for projectional editors and (b) selection changes non-trivially bind to focus changes and code that choose the proper source of selection isn't well portable across editors.

**Comment by solomatov** [comment]
>Create a new API somwhere on the CellContainer level. Don't have a good design for it as (a)selection is represented as a cell list for hybrid editors and as a model list for projectional editors and (b) selection changes non-trivially bind to focus changes and code that choose the proper source of selection isn't well portable across editors.

Eventually we need to adopt such a solution. It's not the only possible selection mechanism (consider diagram editor which won't use SelectionSupport), and we should abstract it away. Please, prepare proposal for such a refactoring for the tomorrow meeting.

**Pull request merged**
