### PR TITLE
fix message controller setup

### PR DESCRIPTION
**Pull request by katepol**
this commit fixes the bug: when cell is attached to cell container with preset message property, NPE is thrown on that message property change

### CODE REVIEW

**Comment by kirelagin** [comment]
With this patch I get NPE in a different place. Somehow, this happens when a cell with non-empty but invalid text is being added; popup position updater handler fires before the view has been attached.

**Comment by katepol** [comment]
I've reproduced the problem in unit tests. I will fix it the next day.

**Comment by solomatov** [comment]
If it leads to the exceptions, I will not merge it until they are fixed.

**Comment by katepol** [comment]
I have fixed the NPE.

**Comment by kirelagin** [comment]
Yep, indeed.

**Pull request merged**
