### PR TITLE
Cell mappers refactoring

### PR DESCRIPTION
**Pull request by katepol**
1) What do you think of CellMapper interface?
2) Should packages 'toUtil' and 'mappers' be merged?

### CODE REVIEW

**Comment by solomatov** [comment]
I don't think creating any common interfaces is a good idea here.

**Comment by katepol** [comment]
should I then inline IndentUtil.updateCounters() and updateBackground() back?

**Comment by solomatov** [comment]
The change looks good. However, there are several problems:
* CellMapper looks quite bag. It looks like a class which was created only to reduce code duplication in background. We need to get rid of them.

**Comment by solomatov** [comment]
Aslo in fa66325 you fixed a bug but didn't provide a unit test. Please, always provide a unit test when you break something.

**Pull request merged**
