### PR TITLE
Refactoring of editing tests

### PR DESCRIPTION
**Pull request by CheatEx**
- Moved most of tests to the base test class so the're also applied to SimpleHybridEditor
 - Fixed up-selection in SimpleHybridEditor
 - Merged copy-paste tests to the base test class

### CODE REVIEW

**Comment by katepol** [comment]
1) BaseHybridEditorTest.registration should be private
2) TokenListEditor.reprint(boolean) seems suspicious to me. Could you please make it more clear?

**Comment by azlobinjb** [comment]
@katepol see the new commits

**Comment by timzam** [comment]
We could make tokenListEditor.myUpdateModel final. I had to search for usages to see if it's changed anywhere. We can make this change later though. So I'm fine.

**Comment by katepol** [comment]
Ok! I merge this

**Pull request merged**
