### PR TITLE
TokenListValidator

### PR DESCRIPTION
**Pull request by timzam**
- New method in HybridEditorSpec: TokenListValidator getTokenListValidator()
- TokenListValidator: void validate(List<Token> tokenList). In this method we make sure that the token list stays valid
- Removed completer parameter in tokenCompletion.getTokenCompletion()
- Removed completer.completeTerminatorToken()
- Now there is no need in the built-in TerminatorToken

Dependent pull requests:
JetBrains/jetpad-ot#52
JetBrains/datapad#8

### CODE REVIEW

**Comment by azlobinjb** [comment]
Is it ok to use TokenListValidator to get proper spacing for SimpleHybridEditor? In this case we could  simplify flow in TokenListEditor so it doesn't reprint what it just parsed and relies on TokenListValidator to get spacing right.

**Comment by timzam** [comment]
The idea was to use it for lexer level validation. The proper spacing could be difficult to obtain without parsing which we use during the reprint.

**Comment by katepol** [comment]
TokenListValidator which silently modifies the tokens list doesn't seem good. More significant name would be better. TokenListUpdater?.. TokensCompletionTransformer?

**Comment by katepol** [comment]
We decided to call it TokensCorrector in the next pull request

**Pull request merged**
