### PR TITLE
introduce message controller

### PR DESCRIPTION
**Pull request by katepol**

### CODE REVIEW

**Comment by katepol** [comment]
I have added the 'show message' popup functionality by Ctrl+1 in addition to Ctrl+F1 because I found out that on Mac OS X there is a system shortcut bound to Ctrl+F1 by default.

**Comment by solomatov** [comment]
Here's my list of required improvements:
1. Rename CellWithMessageStyler to a better name. I think MessageStyler will work. Please, use shorter names when possible.
2. Consider renaming DecorationTrait to MessageTrait. It's nice to have uniform naming in the framework.
3. StyleController names is strange. It doesn't controls anything nor it's a controller in UI sense. Need a better name.
4. Consider replacing custom stylers list with a callback or abstract method.
5. TextEditing.errorStyler() shouldn't be available in TextEditing. TextEditing should be responsible only 
for text editing. Remember Single Responsibility Principle (https://en.wikipedia.org/wiki/Single_responsibility_principle) 
6. BaseCellMapper shouldn't know about messages. Again SRP.
7. Again RootController should have just one method. I wrote about this in my previous review, and you didn't fix it which is bad.

Until you fix these issues, I can't merge it into the repo.

**Comment by katepol** [comment]
Thank you! For something like this I asked you to review me carefully.
6. I didn't like it either and I asked you to look at it closer. 
But the alternatives I see are: 
- modify Cell.BACKGROUND to hold not just the color but some extra String that will stand for CSS underline;
- turn CSS underline into some other thing, red bottom dashed border for example.
7. I thought you meant not to add various install methods for messages support to RootController. OK, sorry.  

I fixed all except 6.

**Comment by solomatov** [comment]
Considering 6. It's actually very easy. Do the following:
1. Introduce error_underline and warning_underline attributes to the Cell.
2. Synchronize them.

The main concern is referencing the MessageController class.

**Comment by katepol** [comment]
I did it, thank you.

**Comment by katepol** [comment]
Ready for review.

**Comment by solomatov** [comment]
I merge it in but could you please RootController install both CellNavController and MessagesController.

**Pull request merged**
