### PR TITLE
Better completions

### PR DESCRIPTION
**Pull request by kirelagin**

### CODE REVIEW

**Comment by solomatov** [comment]
I won't merge this.

**Comment by kirelagin** [comment]
Wait, why:question:

**Comment by solomatov** [comment]
Because you didn't remove "[" ... "]" which I told you about.

**Comment by kirelagin** [comment]
I’m pretty sure I did.

**Comment by kirelagin** [comment]
Damn it, there is another one, now I see. There you go.

**Comment by kirelagin** [comment]
Hm, looks like it won’t update automatically after the pull request is closed. I’m opening a new one.

**Pull request closed without merging**
